# include definitions
include $(SRCDIR)/src.mk
SUBDIRS = 
HOMEDIR = $(DASDIR)/dfs/mods/dbs/dcgw
BASE = dcgw

# file list macros
TXTS += $(USEDIR)/dc.txt $(USEDIR)/msg.txt $(USEDIR)/cc.txt
SRCS += dcgw_dc.c dcgw_dg.c
LIBS = dfs_mod dfs das

# include targets
include $(DASDIR)/tgt.mk

# dependencies
