# include definitions
include $(SRCDIR)/src.mk
SUBDIRS =
HOMEDIR = $(DASDIR)/dfs/mods/dcs/msgout
BASE = msgout

# file list macros
TXTS += $(USEDIR)/msg.txt $(USEDIR)/dc.txt
LIBS = dbr das
SRCS += msgout_dc.c

# include targets
include $(DASDIR)/tgt.mk
