# include definitions
include $(SRCDIR)/src.mk
SUBDIRS =
HOMEDIR = $(DASDIR)/dbr/mods/dcs/inetout
BASE = inetout
LDFLAGS += -N5k

# file list macros
TXTS += $(USEDIR)/dc.txt $(USEDIR)/das.txt $(USEDIR)/msg.txt
LIBS = dbr das

# include targets
include $(DASDIR)/tgt.mk
