# master makefile for eil's source

include $(SRCDIR)/src.mk
BASE = src
SUBDIRS =  lib	eillib
SUBDIRS += memo memo
SUBDIRS += das das
SUBDIRS += diags diags
SUBDIRS += graphics graphics
SUBDIRS += demo srcdemo
SUBDIRS += drs drs
SUBDIRS += audio audio
HOMEDIR = $(SRCDIR)
DOCS = tgt.mk lib.mk dir.mk src.mk
SRCS =
HDRS =
TXTS =

all:
