include $(SRCDIR)/src.mk
BASE = scrpaint
SUBDIRS =
HOMEDIR = $(SRCDIR)/graphics/$(BASE)
SRCS = scrpaint.c
LIBS = curses curses_utils lat eillib
TXTS += $(USEDIR)/msg.txt

include $(SRCDIR)/tgt.mk
scrpaint.o : scrpaint.c
