#! /bin/sh
#__USAGE
#%C	key library name ...
#	Thin cover for wlib to be compatible with ar
#	Supports the following key letters:
#	qcru
#	ru  replace existing modules. u indicates only replace
#	    those which are newer
#	c   create the library (kinda moot)
#	q   quickly append to the end.
#
#	I'm going to punt on this. Forget the key letters.
#	Always create a new library.
#
#	Increased the record size to 32 to accomodate a large library
#	in the perl 5.003 distribution

if [ $# -lt 3 ]; then
  use $0
  exit 1
fi
shift
library=$1
shift
wlib -p=32 -n $library `for i in $*; do echo "+$i \\c"; done`
