#! /bin/sh

#__USAGE
#%C	[-od1] [-c <n>] directory [directory ...]
#	Perform Archive Operations for an Experiment
#	-c Specify the number of copies to be made (default 2)
#	Examples:
#	  archive 930506.2
#	  archive func/930506.2
#	  archive //2/home/hox/930506.2
#
typeset drive=od0 sval dest homedir invar copies=2

while getopts "o:c:" option; do
  case $option in
	o) drive="o$OPTARG";;
	c) copies=$OPTARG;;
	\?) echo; exit 1;;
	*) echo Unsupported option: -$option; exit 1;;
  esac
done
let sval=$OPTIND-1
shift $sval

[ -z "$OD_NODE" ] && export OD_NODE=1
[ -z "$Experiment" ] && {
  echo archive: Experiment is undefined >&2
  exit 1
}
homedir=~$Experiment
case $homedir in
  ~*)
	echo archive: Cannot determine home directory for Experiment \"$Experiment\" >&2
	exit 1;;
  \/\/[0-9]*)
	echo Home directory is node-specific! >&2
	exit 1;;
esac
dest=//$OD_NODE/$drive$homedir

for j in $*; do
  if [ ! -d "$j" ] ; then
	echo Argument $j is not a directory
	exit 1
  fi
  k=${j#*$homedir/}
  echo Directory $j will be backed up to $dest/$k
done
echo Archives will be written to $copies disks
echo -n "Is that correct? [n/y] "
read j
case $j in
  [yY]*) : ;;
  *) exit 1;;
esac

if [ -b //$OD_NODE/dev/$drive ]; then
  echo Optical Disk Backup
  i=1
  while [ $i -le $copies ]; do
	if [ -d //$OD_NODE/$drive ]; then
	  odout $drive || exit 1
	fi
	while :; do
	  echo Insert Optical Disk $i and Press Return when Ready or N to skip: \\c
	  read invar
	  case $invar in
		[nN]*) break;;
	  esac
	  if odin -w $drive; then break; fi
	done
	if [ ! -d //$OD_NODE/$drive ]; then break; fi
	for j in $*; do
	  k=${j#*$homedir/}
	  df -h //$OD_NODE/$drive
	  echo Optical Disk Backup of $j Proceeding ...
	  umask o+rx,g+rwx
	  cp -frc $j $dest/$k
	  echo Optical Backup $i to $dest/$k Complete
	done
	let i=$i+1
  done
  if [ -d //$OD_NODE/$drive ]; then
	odout -e $drive
	odin $drive
  fi
  let i=$i-1
  if [ $i -gt 0 ]; then
	copy=copy
	[ $i -gt 1 ] && copy=copies
	for j in $*; do
	  k=${j#*$homedir/}
	  echo $i $copy written to $dest/$k |
		mail -s "$dest/$k" nort@bottesini.harvard.edu
	done
  fi
else
  echo archive: Cannot locate Optical Drive
fi
