#! /bin/sh
#__USAGE
#%C	[-P] [-C] other options
#	cpp is a wrapper for wcc to make it work like other cpp's
#	-P omit #line directives from the output
#	-C pass comments through to the output
typeset lines=l comments="" redir=""
while :; do
  case $1 in
	-P) lines=""; shift; continue;;
	-C) comments=c; shift; continue;;
  esac
  break
done
if [ ! -t 0 ]; then
  cat >$$.tmp.c
  redir=$$.tmp.c
fi
cc -c -Wc,-p$lines$comments -Wc,-pw=0 $* $redir | awk 'NR>1||NF>0 {print}'
[ -n "$redir" ] && rm -f $redir
