#! /bin/sh
# setuid script to distribute files into a target directory.
# I will deem it okay to copy files if the user has write
# permission in the target directory
#__USAGE
#%C	target_dir file [file ...]
typeset tgt ans opts
opts=-vpn
if [ "x$1" = "x-f" ]; then
  shift 1
  opts=-vpf
fi
tgt=$1
shift 1
if [ ! -d "$tgt" ]; then
  echo Target \"$tgt\" is not a directory >&2
  exit 1
fi
ans=`/usr/local/bin/unsu /bin/sh -c "if [ -w \"$tgt\" ]; then echo yes; else echo no; fi"`
if [ "$ans" != "yes" ]; then
  echo You do not have write permission in $tgt >&2
  exit 1
fi
/bin/cp $opts $* $tgt
exit 0
