#! /bin/sh

#__USAGE
#%C	<node number>
#%C	<directory>
#	Runs chkfsys on the designated node's root or the designated
#	filesystem
typeset response=y fsys node
[ -z "$1" ] && echo fixdisk: No arguments specified >&2 && exit 1
fsys=$1
[ ! -d "$fsys" ] && fsys=//$fsys/
fsys=`/usr/bin/fullpath -t $fsys`
[ ! -d $fsys ] && {
  echo fixdisk: Unable to locate filesystem for $1 >&2
  exit 1
}
node=${fsys#//}
node=${node%%/*}

while [ "$response" = "y" ]; do
  /usr/bin/on -f $node /bin/chkfsys -r -u $fsys
  /bin/stty +echo +edit
  if [ `id -run` = tfh ]; then
	echo "Wanna run it again, HUH? Wanna?: [n/y] \\c"
  else
	echo "Should we run chkfsys again? [n/y] \\c"
  fi
  read j
  response=n
  case $j in
    [yY]*)
	  if [ `id -run` = tfh ]; then
		echo "\n\nHA HA HA! NO you fool! The answer is NO!\n\a"
		sleep 2
	  else
	    response=y
	  fi;;
  esac
done
