#! /usr/bin/env ENV="" /bin/sh
# This script should get a little more error checking before being
# made setuid. It has been cleared for use by root, blocking obvious
# security holes.

#__USAGE
#%C	<device>
#	initialise a floppy for QNX raw data

case $# in
  0) exec use $0;;
esac

for dev
do
  echo formatting $dev
  echo insert floppy in $dev
  if /bin/fdformat -ap $dev
  then
	/bin/umount $dev
	echo block checking $dev
	if /bin/dcheck -V $dev
	then
	  echo "Disk suitable for archiving"
	  exit 0
	else
	  echo "Disk NOT suitable for archiving: bad blocks"
	  exit 1
	fi
  else
	echo "Disk NOT suitable for archiving: error in fdformat"
	exit 1
  fi
done
