#! /bin/sh

#__USAGE
#%C	<device>
#	initialise a floppy for QNX raw data

case $# in
	0) exec use $0;;
esac

for dev
do
	echo formatting $dev
	echo insert floppy in $dev
	if fdformat -ap $dev
	then
		sleep 10
		echo block checking $dev
		if dcheck -V $dev
		then
			echo "Disk suitable for archiving"
			exit 0
		else
			echo "Disk NOT suitable for archiving: bad blocks"
			exit 1
		fi
	else
		echo "Disk NOT suitable for archiving: error in fdformat"
		exit 1
	fi
done
