#! /usr/local/bin/perl
#__USAGE
#%C	[-rel|dev] [-v] document [ document ... ]
#	-dev Produce development version (default)
#	-rel Produce release version
#	-v   Explicitly list which pieces are used
#
# Puts together pieces to create the specified document.
# Documents may be of the form:
#
#   [http:][//host]/path
#
# Where "host" is one of:
#     www.arp.harvard.edu (default)
#     www.abcd.harvard.edu
#     www-safety.deas.harvard.edu
#     www.theater.harvard.edu
# or one of the shortcuts:
#     arp, abcd, safety or theater.

use lib "//23/usr/local/httpd/cgi/dev";
use Makepage;

$| = 1;

my $rel = "dev";
my $verbose = 0;
$ENV{PATH} = "/bin:/usr/bin:/usr/local/bin";

for my $arg ( @ARGV ) {
  if ( $arg eq "-rel" ) {
	$rel = "rel";
  } elsif ( $arg eq "-v" ) {
	$verbose++;
  } else {
	my $url = Makepage::URL( $arg );
	if ( @{$url->{errors}} > 0 ) {
	  die @{$url->{errors}};
	}
	$url->makepage( $rel ) ||
	  die @{$url->{errors}};
	print @{$url->{sources}} if $verbose;
  }
}
