#! /bin/sh

#__USAGE
#%C	[-w] <drive>
#	Mount Optical Disk
#	<drive> is one of od0 or od1
#	-w requests that the disk be mounted for r/w access.
#
#	You must belong to group "root" in order to mount WORM disks
#	for write.
unset mountmode

while getopts "w" option; do
  case $option in
	w) mountmode=writable;;
	?) echo Illegal option -$OPTARG;;
	*) echo Unsupported option -$option;;
  esac
done

if [ $OPTIND -le $# ]; then
  eval drive=\${$OPTIND}
else unset drive
fi

case $drive in
  od[0-2]) :;;
  *) echo Must specify od0, od1 or od2; exit 1;;
esac

# Optical Drive Disk In
if [ -z "$OD_NODE" ]; then
   OD_NODE=$NODE
fi
echo Looking at //$OD_NODE/dev/$drive
bdrive=//$OD_NODE/dev/$drive
mdrive=//$OD_NODE/$drive

if [ ! -b $bdrive ]; then
  echo Unable to locate optical drive: Is OD_NODE defined?
  exit 1
fi

set -- `/usr/bin/fullpath $bdrive`
[ -n "$3" ] || exit 1
if /bin/expr "$3" : //$OD_NODE/dev/\* >/dev/null ; then
  if [ "$bdrive" != "$3" ]; then
	echo $bdrive is really $3
	bdrive=$3
  fi
else
  echo $*: get help!
  exit 1
fi

if [ -d $mdrive ]; then
  echo Optical Disk $mdrive already mounted
  exit 1
else
  # Do an extra umount just to make sure:
  on -n $OD_NODE /bin/umount $bdrive
fi

until /bin/fdisk $bdrive query total >/dev/null ; do
  echo Unable to query optical disk: Is it inserted in drive?
  exit 1
done

# Determine disk type based on number of cylinders returned by fdisk
total=`/bin/fdisk $bdrive query total`
case $total in
  311) disktype=Erasable;;
  1024) disktype=WORM;;
  *)
	echo "Oops! New SCSI Driver"
	total=`/bin/fdisk $bdrive info |
			/bin/awk '/Total Sectors/ { print $NF }'`
	case $total in
	  637440) disktype=Erasable;;
	  2097657) disktype=WORM;;
	  *) echo "Unknown disk size:"
		 echo   Ask Norton to check Omnistor configuration
		 exit 1;;
	esac;;
esac

# Determine whether to mount for r/w access.
if [ "$mountmode" = writable ] ; then
  if [ $total -eq 311 -o `id -g` -eq 0 ] ; then
	unset mountmode
	access="R/W"
  else
	echo You must belong to group "root" to mount WORM for R/W access.
	exit 1
  fi
else
  mountmode=-r
  access="READ ONLY"
fi

if eval "//$OD_NODE /bin/mount -p $bdrive ${bdrive}t77 $mdrive $mountmode"
then
  echo $disktype Disk $mdrive mounted successfully for $access access
  if [ -x /usr/bin/scsi_util ]; then
	/usr/bin/scsi_util -n $OD_NODE $bdrive lock
  else
	echo You are missing scsi_util. Please osupdate
  fi
else
  echo $disktype Disk mount failed on node $OD_NODE
  exit 1
fi
