#! /bin/sh

#__USAGE
#%C	[-w] <drive>
#	Mount Optical Disk
#	<drive> is one of od0 or od1
#	-w requests that the disk be mounted for r/w access.
#
#	You must belong to group "root" in order to mount WORM disks
#	for write.
unset mountmode

while getopts "w" option; do
  case $option in
	w) mountmode=writable;;
	?) echo Illegal option -$OPTARG;;
	*) echo Unsupported option -$option;;
  esac
done

if [ $OPTIND -le $# ]; then
  eval drive=\${$OPTIND}
else unset drive
fi

case $drive in
  od0) :;;
  od1) :;;
  *) echo Must specify od0 or od1; exit 1;;
esac

# Optical Drive Disk In
if [ -z "$OD_NODE" ]; then
   OD_NODE=$NODE
fi
echo Looking at //$OD_NODE/dev/$drive
bdrive=//$OD_NODE/dev/$drive
mdrive=//$OD_NODE/$drive

if [ ! -b $bdrive ]; then
  echo Unable to locate optical drive: Is OD_NODE defined?
  exit 1
fi

if [ -d $mdrive ]; then
  echo Optical Disk $mdrive already mounted
  exit 1
else
  # Do an extra umount just to make sure:
  umount $bdrive
fi

until fdisk $bdrive query total >/dev/null ; do
  echo Unable to query optical disk: Is it inserted in drive?
  exit 1
done

# Determine disk type based on number of cylinders returned by fdisk
total=`fdisk $bdrive query total`
case $total in
  311) disktype=Erasable;;
  1024) disktype=WORM;;
  *) echo Unknown disk size: check Omnistor configuration; exit 1;;
esac

# Determine whether to mount for r/w access.
if [ "$mountmode" = writable ] ; then
  if [ $total -eq 311 -o `id -g` -eq 0 ] ; then
	unset mountmode
	access="R/W"
  else
	echo You must belong to group "root" to mount WORM for R/W access.
	exit 1
  fi
else
  mountmode=-r
  access="READ ONLY"
fi

if mount -p $bdrive ${bdrive}t77 $mdrive $mountmode
then
  echo $disktype Disk $mdrive mounted successfully for $access access
else
  echo $disktype Disk mount failed on node $OD_NODE
  exit 1
fi
