#! /bin/sh
# QNX 4.25 Installation over the network.
#__USAGE
#%C	[-ufRlo] [-d <driver> [-p <param>]] -t <target node>
#	-t <target node> specify target node (Required)
#	-u Upgrade only: don't reinitialize the disk
#	-f Interactively set fdisk parameters
#	-d <driver> specify disk driver. Default is to use disktrap
#	-p <driver parameters> specify driver parameters
#	-R Don't ask (Rambo mode)
#	-l Disk is very large: add a special boot partition
#	-o Skip osupdate step (perform that step manually)
# Installs operating system from current node or SRCNODE
# if defined.
#

function nl_error {
  echo "netinstall5: $*" >&2
  exit 1
}

typeset UPGRADE FDISK TGTNODE DISKDRV DISKPARM LOCAL
typeset DosF DosQuote NetA NetN NetW Tinit Mouse Int10
typeset Dev DevCon DevSer DevPar FsysFl
typeset opts excl n j option isFlt notFlt
UPGRADE=no
FDISK=no
LARGE=no
RAMBO=no
OSUPDATE=yes

DISKDRV=query
# DISKPARM='fsys -Ndsk0 -n0=hd0. -n5=cd0. eide -a1f0 -i14'
LOCAL=""
while getopts "uUd:p:t:flRo" option; do
  case $option in
	[uU]) UPGRADE=yes;;
	d) DISKDRV=$OPTARG; DISKPARM="";;
	p) DISKPARM="$OPTARG";;
	t) TGTNODE=$OPTARG;;
	f) FDISK=yes;;
	l) LARGE=yes;;
	R) RAMBO=yes;;
	o) OSUPDATE=no;;
	?) echo; exit 1;;
	*) nl_error Unsupported option: -$option;;
  esac
done

[ -z "$SRCNODE" -a "$NODE" = "1" ] && SRCNODE=1
[ -z "$SRCNODE" ] && nl_error "No SRCNODE specified"
[ -z "$TGTNODE" ] && nl_error Must specify a target node

function hitanykey {
  if [ $RAMBO = no ]; then
	echo
	echo Continue? [Y/N/R]: \\c; read j
	case $j in
	  [nN]*) exit 1;;
	  [rR]*) export RAMBO=yes;;
	esac
  fi
}

#----------------------------------------------------------------
# query_config() looks for the currently running programs
# and outputs configuration to stdout for assignments
#  query_config program default_args
# example:
#  var=`query_config Net.ether1000 " -l2 -n2 -6 -s16"`
# The defaults are used if the program is not currently running.
# If no default args are specified and the program is not 
# currently running, the variable will be empty. If the defaults
# are specified and the program is not currently running,
# a sharp is prefixed, allowing the administrator to uncomment
# the definition if desired.
#
# The output does not include a trailing ampersand, since
# I don't have a way of determining if that is required or not.
# This approach will not work with all programs, since some
# may alter their command lines or fork. Others may require input
# redirection, which must be queried further
#----------------------------------------------------------------
function query_config {
  typeset prog
  echo Querying Current Configuration of $1 >&2
  prog=`sin -h -n $TGTNODE -P $1 format a 2>/dev/null |
		egrep "^$1( .*|)$"`
  if [ -z "$prog" ]; then
	if [ -n "$2" ]; then
	  prog="# $1$2"
	  # echo "Configuration not found, using default: $prog" >&2
	else
	  prog=""
	fi
  fi
  echo $prog
}

echo QNX 4.25 Network Installation\\c
[ $UPGRADE = yes ] && echo " Upgrade\\c"
echo " to node $TGTNODE from node $SRCNODE"

#----------------------------------------------------------------
# Verify that configuration options are defined
#----------------------------------------------------------------
opts=`grep ^$TGTNODE: //$SRCNODE/etc/config/node.map | cut -f 9 -d:`
excl=${opts##*,}
opts=${opts%%,*}
[ -n "$opts" ] ||
  nl_error No configuration options for node $TGTNODE in //$SRCNODE/etc/config/node.map

case $opts in
  *E*) isFlt=""; notFlt="# ";;
  *)   isFlt="# "; notFlt="";;
esac

#----------------------------------------------------------------
# Check for netinstall options
#----------------------------------------------------------------
opts=`grep ^$TGTNODE: //$SRCNODE/etc/config/node.map | cut -f 10 -d:`
case $opts in
  *L*) LOCAL="-l";;
esac

#----------------------------------------------------------------
# Query configurations
#----------------------------------------------------------------
Dev=`sin -n $TGTNODE -P Dev -h format a | grep "Dev "`
DevCon=`sin -n $TGTNODE -P Dev -h format a | egrep "ansi|con"`
DevSer=`query_config Dev.ser " "`
DevPar=`query_config Dev.par " "`
FsysFl=`query_config Fsys.floppy " "`
DosF=`query_config Dosfsys`
if [ -n "$DosF" ]; then
  DosQuote=""
else
  DosF="# Dosfsys "
  DosQuote="# "
fi
Mouse=`query_config Mouse`
if [ -n "$Mouse" ]; then
  Mouse="$Mouse <"`sin -n $TGTNODE -P Mouse -h fd |
	awk '/0 - / { print $3}'`
else
  Mouse="# Mouse </dev/ser1 "
fi
Int10=`query_config int10 " "`

Net=`query_config Net " -T"`
# NetA=`query_config Net.arcnet " -s "`
# NetN=`query_config Net.ether1000 " -l2 -n2 -6 -s16 "`
# NetW=`query_config Net.ether8003 " -l2 -n2 "`

if [ -z "$isFlt" ]; then
  Tinit='tinit -T /dev/con[2-9] -c "/bin/login -f flight" -t /dev/con1 '
else
  Tinit=`query_config tinit ' -T /dev/con[1-9] -t /dev/con1 '`
  Tinit="${Tinit###}"
  case $Tinit in
	*/ram/bin*) Tinit='tinit -T /dev/con[1-9] -t /dev/con1';;
	*) :;;
  esac
fi

#----------------------------------------------------------------
# Shutdown interactive operations on the target node
#----------------------------------------------------------------
echo Shutting down interactive operations on node $TGTNODE
on -n $TGTNODE slay -f tinit login
if [ -f //1/usr/local/lib/src/upgrade.fld ]; then
  for i in //$TGTNODE/dev/con*; do
	scrpaint -v //1/usr/local/lib/src/upgrade > $i
  done
  stty +fix +edit
else
  echo Notification screen is missing
  for i in //$TGTNODE/dev/con*; do
	echo \\f\\n\\n\\nSystem undergoing upgrade > $i
	echo \\n\\n\\nPlease do not disturb > $i
  done
fi

#----------------------------------------------------------------
# Check to see that we can talk to the remote node
#----------------------------------------------------------------
sin -n$TGTNODE info >/dev/null ||
  nl_error Cannot see target node $TGTNODE

# export TZ=est05edt04,M4.1.0/2,M10.5.0/2
echo Setting time from node $NODE
rtc -s net $TGTNODE
on -n $TGTNODE rtc $LOCAL -s hw
hitanykey

#----------------------------------------------------------------
# Install the file system if it isn't already
#----------------------------------------------------------------
namewait -n $TGTNODE -t 0 qnx/fsys 2>/dev/null ||
namewait -n $TGTNODE -t 0 qnx/fsys32 2>/dev/null || {
  echo Installing File System on node $TGTNODE
  on -n $TGTNODE -t //$TGTNODE/dev/con1 //$SRCNODE/bin/Fsys
}

#----------------------------------------------------------------
# Install the driver if it isn't already
#----------------------------------------------------------------
if [ ! -b //$TGTNODE/dev/hd0 -a ! -b //$TGTNODE/dev/hd0.0 ]; then
  if [ $DISKDRV = query ]; then
    echo "Attempting to identify correct disk driver"
    d=`on -f$TGTNODE //$SRCNODE/bin/disktrap query`
    [ -z "$d" ] && nl_error disktrap failed
    DISKDRV=${d%% *}
    DISKPARM=${d#$DISKDRV}
    DISKPARM=${DISKPARM# }
    echo "disktrap returned $DISKDRV $DISKPARM"
	if [ "$DISKDRV" = Fsys.eide -a -z "$DISKPARM" ]; then
	  DISKPARM='fsys -Ndsk0 -n0=hd0. -n5=cd0. eide'
	  echo "Adding additional parameters: $DISKPARM"
	fi
    hitanykey
  fi
  echo Installing Disk Driver $DISKDRV on node $TGTNODE
  on -f $TGTNODE -t //$TGTNODE/dev/con1 $DISKDRV $DISKPARM
  while [ ! -b //$TGTNODE/dev/hd0 -a ! -b //$TGTNODE/dev/hd0.0 ]; do
	echo "Waiting for //$TGTNODE/dev/hd0[.0] to appear..."
	sleep 2
  done
fi
rawdisk=''
for d in hd0 hd0.0; do
  [ -b //$TGTNODE/dev/$d ] && rawdisk=$d
done
[ -z "$rawdisk" ] && nl_error Cannot locate raw disk
rawdisk=//$TGTNODE/dev/$rawdisk

#----------------------------------------------------------------
# Initialize the disk unless upgrading
#----------------------------------------------------------------
if [ $UPGRADE != yes ]; then
  if [ $FDISK = yes ]; then fdisk $rawdisk
  else
	[ $LARGE = yes ] && fdisk $rawdisk ADD QNZ 4m
	fdisk $rawdisk ADD QNX ALL
  fi
  fdisk $rawdisk show
  hitanykey

  on -f $TGTNODE mount -p $rawdisk
  if [ $LARGE = yes ]; then
	dinit -hq ${rawdisk}t79
	on -f $TGTNODE mount ${rawdisk}t79 //$TGTNODE/hd0
	on -n $TGTNODE dcheck -m //$TGTNODE/hd0
    hitanykey
  fi
  dinit -hq ${rawdisk}t77
  on -f $TGTNODE mount ${rawdisk}t77 //$TGTNODE/hd
  on -n $TGTNODE dcheck -m //$TGTNODE/hd
  hitanykey
  echo Modifying the prefix table for node $TGTNODE
  on -n $TGTNODE prefix -R /=//$TGTNODE/hd
  prefix -n$TGTNODE
  fullpath //$TGTNODE/
else
  if [ ! -b ${rawdisk}t77 ]; then
	on -f $TGTNODE mount -p $rawdisk ${rawdisk}t77 //$TGTNODE/hd
	on -f $TGTNODE prefix -R /=//$TGTNODE/hd
  fi
  # Would like to check to make sure I am modifying the right thing
  echo Please verify that I am addressing the correct disk:
  fullpath //$TGTNODE/
  hitanykey
  echo Installing new bootstrap loader
  dinit -hb ${rawdisk}t77
fi

#----------------------------------------------------------------
# Copy over file systems via osupdate
#----------------------------------------------------------------
echo Disks mounted: Ready to begin file copying
hitanykey

if [ "$OSUPDATE" = "yes" ]; then
  osupdate -f OSU.425 $SRCNODE $TGTNODE
  hitanykey
  if [ $TGTNODE != 1 ]; then
   osupdate 1 $TGTNODE
   hitanykey
  fi
else
  echo Skipping osupdate: perform manual copy now
  hitanykey
fi

#----------------------------------------------------------------
# Perform configuration
#----------------------------------------------------------------
typeset sysinit
cd //$TGTNODE/etc/config
sysinit=sysinit.$TGTNODE
[ -f $sysinit ] && sysinit=sysinit.u

pwd
echo Creating $sysinit
cat > $sysinit <<-END_OF_FILE
#----------------------------------------------------------------
# Sysinit for Node $TGTNODE booting from disk
#----------------------------------------------------------------
set -i
${isFlt}export TZ=utc00
${notFlt}export TZ=est05edt04,M4.1.0/2,M10.5.0/2
${notFlt}[ -x /etc/config/TZ.init ] && . /etc/config/TZ.init
rtclocal='$LOCAL'
rtc \$rtclocal hw
${Dev} &
${DevCon} &
${DevSer} &
${DevPar} &

reopen //0/dev/con1
echo Booting Node \$NODE from disk \(\`/usr/bin/fullpath -t \$0\`\)

emu87 &
${FsysFl} &
${DosF} &
${DosQuote}echo Waiting for Dosfsys to initialize...
${DosQuote}while [ ! -d /dos/c ]; do sleep 2; done
${DosQuote}echo Continuing

#----------------------------------------------------------------
# Start up the QNX Network
#----------------------------------------------------------------
${Net} &
netmap -f
END_OF_FILE

sin -n $TGTNODE -h -P Net. format a |
  while read prog; do echo "$prog &"; done >> $sysinit

cat >> $sysinit <<-END_OF_FILE
${notFlt}. /etc/config/sysinit.all

#----------------------------------------------------------------
# Start up Mouse and/or Graphics Drivers
#----------------------------------------------------------------
${Mouse} &
${Int10} &

#----------------------------------------------------------------
# Start logins
#----------------------------------------------------------------
${Tinit} &
END_OF_FILE

echo Transferring licenses
license //${SRCNODE:-1}/etc/licenses //$TGTNODE/etc/licenses
hitanykey

echo \\nCreating a boot image
typeset PROC32 image
cpu=`sin -n$TGTNODE -h net | cut -c 13-15`
case $cpu in
  286) PROC32=no;;
  386) PROC32=yes;;
  486) PROC32=yes;;
  586) PROC32=yes;;
  686) PROC32=yes;;
  *)   PROC32=yes;;
esac
if [ $PROC32 = yes ]; then image=hard.$TGTNODE
else
  echo "AWK!!! You can't install 4.25 on a 286!" >&2
  exit 1
fi
cd //$SRCNODE/boot/build
if [ -f $image ]; then mv -vf $image $image.old; fi

#--------------------------------
# Intro to the 32-bit OS version
#--------------------------------
cat >$image <<-END_OF_FILE
/boot/sys/boot
\$ boot -v

/boot/sys/Proc32
\$ Proc32 -l $TGTNODE

/boot/sys/Slib32
\$ Slib32

/boot/sys/Slib16
\$ Slib16

/bin/Fsys
\$ Fsys

/bin/$DISKDRV
\$ $DISKDRV $DISKPARM

/bin/mount
\$ mount -p $rawdisk ${rawdisk}t77 /

/bin/sinit
\$ sinit  TERM=qnx
END_OF_FILE

cd //$SRCNODE/boot
on -f $SRCNODE make b=$image d=$DISKDRV
if [ $LARGE = yes ]; then
  cp //$TGTNODE/hd0/.boot //$TGTNODE/hd0/.altboot
  cp images/$image //$TGTNODE/hd0/.boot

  fdisk //$TGTNODE/dev/hd0 loader
  fdisk //$TGTNODE/dev/hd0 boot QNZ
else
  cp //$TGTNODE/.boot //$TGTNODE/.altboot
  cp images/$image //$TGTNODE/.boot

  fdisk $rawdisk loader
  fdisk $rawdisk boot QNX
fi

echo \\n\\nInstallation of QNX 4.25 Completed\\n\\n
