#! /bin/sh
#__USAGE
#%C	<options>
#	-w list all fields
#	-l list lan information for each node
#	-c list configuration fields for each node
#	-f <fields> list explicit fields (see node.map)
#	   e.g.  noderpt -f 1,2,4 (equivalent to default)
#
typeset FIELDS=1,2,4

function nl_error {
  echo noderpt: $* >&2
  exit 1
}

typeset SCRIPT=/usr/local/lib/src/noderpt.awk
[ -f $SCRIPT ] || nl_error Cannot locate script file $SCRIPT

typeset MAP=//1/etc/config/node.map
if [ ! -f "$MAP" ]; then
  MAP=/etc/config/node.map
  [ -f "$MAP" ] || nl_error Cannot locate node.map
  echo Using non-autoratative node.map file
fi

while getopts "wlcf:" option; do
  case $option in
	w) FIELDS="";;
	f) FIELDS=$OPTARG;;
	l) FIELDS=1-3,5-7;;
	c) FIELDS=1,2,8,9;;
	?) echo; exit 1;;
	*) echo Unsupported option: -$option >&2; exit 1;;
  esac
done

if [ -t 1 ]; then
  exec /bin/sh -c "$0 $* | less"
fi

if [ -n "$FIELDS" ]; then
  cut -d: -s -f $FIELDS $MAP | awk -f $SCRIPT -
else
  awk -f $SCRIPT $MAP
fi
