#! /bin/sh
#__USAGE
#%C	<options>
#	-w list all fields
#	-l list lan information for each node
#	-c list configuration fields for each node
#	-f <fields> list explicit fields (see node.map)
#	   e.g.  noderpt -f 1,2,4 (equivalent to default)
#
typeset FIELDS=1,2,4

typeset SCRIPT=/usr/local/lib/src/noderpt.awk

if [ ! -f $SCRIPT ]; then
  echo Cannot locate script file $SCRIPT >&2
  exit 1
fi

while getopts "wlcf:" option; do
  case $option in
	w) FIELDS="";;
	f) FIELDS=$OPTARG;;
	l) FIELDS=1-3,5-7;;
	c) FIELDS=1,2,8,9;;
	?) echo; exit 1;;
	*) echo Unsupported option: -$option >&2; exit 1;;
  esac
done

if [ -n "$FIELDS" ]; then
  cut -d: -s -f $FIELDS /etc/config/node.map | awk -f $SCRIPT -
else
  awk -f $SCRIPT /etc/config/node.map
fi
