#! /bin/sh
# odinit: Initialize an optical disk
#   Must be superuser to run this: not setuid.
#__USAGE
#%C	<drive>
#	Where <drive> is od0 or od1
#
if [ `id -u` -ne 0 ] ; then
  echo You must be root to initialize optical disks
  exit 1
fi

drive=$1

case $drive in
  od0) :;;
  od1) :;;
  *) echo Must specify od0 or od1; exit 1;;
esac

bdrive=//$NODE/dev/$drive
set -- `fullpath $bdrive`
[ -n "$3" ] || exit 1
[ "$bdrive" = "$3" ] || {
  echo "$bdrive is really $3"
  bdrive=$3
}

if [ ! -b $bdrive ] ; then
  echo Optical disk drive not located:
  echo   You may need to reboot with the optical drive
  echo   powered up and connected.
  exit 1
fi

if [ -d /$drive ] ; then
  echo Optical disk is mounted! It must not require initialization.
  exit 1
fi

# Do an extra umount just to make sure:
umount $bdrive
fdisk /dev/$drive query total >/dev/null || {
  echo Unable to query optical disk: Is in inserted in drive?
  exit 1
}

# testint exits if the argument passed is not an integer
function test_int {
  expr "$1" : "^[0-9]*$" >/dev/null || {
	echo Non-integral Value \"$1\" returned from fdisk
	exit 1
  }
}

total=`fdisk $bdrive query total`; test_int "$total"
free=`fdisk $bdrive query free`; test_int "$free"
qnx=`fdisk $bdrive query qnx`; test_int "$qnx"

if [ $total -eq 0 ] ; then
  echo There appears to be no space at all on the disk!
  exit 1
fi

if [ $free -ne $total -o $qnx -ne 0 ] ; then
  echo Disk appears to be previously initialized:
  fdisk $bdrive show
  exit 1
fi

case $total in
  311) echo Disk is believed to be Erasable, based on total size of 311MB;;
  1024) echo Disk is believed to be WORM, based on total size of 1024MB;;
  *) echo Disk size $total is unrecognized: check Omnicache configuration;
     exit 1;;
esac
echo "Is this correct? \\c"
read j
case $j in
  [yY]*) : ;;
  *) echo Check Omnicache configuration; exit 1;;
esac

echo Proceeding with initialization
if fdisk $bdrive add QNX ALL &&
   fdisk $bdrive loader &&
   mount -p $bdrive &&
   dinit -h ${bdrive}t77 ; then
  umount $bdrive
  echo Disk is initialized: Mount using odin or archive utility.
else
  echo Disk initialization apparently failed: Get Help!
fi

