#! /bin/sh
# This is a script to change passwords on node 1 and (hopefully)
# distribute them to the network
#__USAGE
#%C
#	Change your password throughout the QNX network
#
if [ -d //1/etc ]; then
  cd //1/etc
  on -f 1 passwd $*
  for i in `awk 'BEGIN { FS=":" }
	  /[0-9]/ { if (NF > 3 && $1 != 1 && $1 == $3) print $1 }
	  ' config/node.map`; do
	on -n 1 sh -c "if [ -d //$i/etc ]; then
	  cp -vpn passwd shadow group //$i/etc; fi"
  done
else
  echo Node 1 is not currently reachable.
fi
