#! /usr/bin/env ENV="" /bin/sh
#__USAGE
#%C	file [file]
#
if [ `/usr/bin/id -g` != 0 ]; then
  for i in $*; do
	/usr/bin/ident -q $i | /bin/grep -q "seteuid.oui,v" ||
	  { echo Cannot promote $i >&2; exit 1; }
  done
fi
/bin/chown root:root $*
/bin/chmod o-rw,g+wx,u+xs $*
