#! /bin/sh
#__USAGE
#%C	file [file]
#
if [ `id -g` != 0 ]; then
  for i in $*; do
	ident -q $i | grep -q -E "(colmain.skel,v)|(srvmain.c,v)" ||
	  { echo Cannot promote $i >&2; exit 1; }
  done
fi
chown root:root $*
chmod o-w,g+wx,u+xs $*
