#! /bin/sh
#__USAGE
#%C	[-l] [-u] [[[[CC]YY]MM]DD]hhmm[.SS]
#	Sets time on the current node to the specified time.
#	-u Specified time is UTC rather than local time
#%C	[-l] -n node
#	Sets time on the current node from the specified node
#In either case:
#	-l Set hardware clock to local time
#
#	The -l switch is used on nodes which are configured to
#	boot either QNX or DOS. DOS requires that the hardware
#	clock record local time, whereas QNX prefers UTC.
#	If you are uncertain whether to use this option, look
#	for the "rtc" command in your node's /etc/config/sysinit.n
#	(where n is your node number). If rtc has a -l option
#	there, you should use a -l option here.

function rpterror {
  echo settime: $* >&2
  exit 1
}

# Obtain target node configuration
dst=$NODE
map=/etc/config/node.map
if [ -f $map ]; then
  nodeadmin=`/bin/grep -i ^$dst: $map | /usr/bin/cut -f 8 -d:`
fi

uid=`/usr/bin/id -un`
[ "$uid" = "root" ] || rpterror must run as root

uid=`/usr/bin/id -run`
if [ -z "$uid" ]; then rpterror No user id found!
elif [ "$uid" != "root" ]; then
  if [ -n "$nodeadmin" ]; then
	for i in $nodeadmin; do
	  if [ "$uid" = "$i" ]; then uid=""; break; fi
	done
  fi
  if [ -n "$uid" ]; then
	rpterror User $uid is not node administrator for node $dst
  fi
fi

typeset LOCAL UTIME NETTIME
while getopts "uln:" option; do
  case $option in
	l) LOCAL="-l";;
	u) UTIME="-u";;
	n) NETTIME=$OPTARG;;
	\?) echo; exit 1;;
	*) rpterror Unsupported option: -$option;;
  esac
done
let sval=$OPTIND-1
shift $sval

if [ -n "$NETTIME" ]; then
  rtc net $NETTIME && rtc $LOCAL -s hw ||
	rpterror Error setting time $1
else
  [ -z "$1" ] && rpterror No time specified
  date $UTIME $1 && rtc $LOCAL -s hw ||
	rpterror Error setting time $1
fi
exit 0
