#! /usr/bin/env ENV="" /bin/sh
#__USAGE
#%C
#	Suspends the clock, so it won't interfere with display
#%C	go
#	Restarts the clock
if [ "$1" = "go" ]; then /bin/slay -fu date clock
else /bin/slay -fh date clock
fi
