#! /bin/sh
#__USAGE
#%C	[<directory>]
#Locates the appropriate bin directories which correspond
#to the specified directory.

typeset appname=`basename $0`
function nl_error {
  echo $appname: $* >&2
  exit 1
}

dir=$1
[ -z "$dir" ] && dir='.'
dir=`fullpath -t $dir`
[ -d "$dir" ] || {
  echo Unable to locate directory "$dir" >&2
  exit 1
}
typeset VERSION MYPATH
[ -f "$dir/VERSION" ] && VERSION=`cat $dir/VERSION`
[ -z "$VERSION" ] && VERSION="1.0"
[ -f "$dir/tm.dac" ] || nl_error Unable to locate $dir/tm.dac

typeset cur_version
[ -f VERSION ] && cur_version=`cat VERSION`
[ -z "$cur_version" ] && cur_version="1.0"
if [ -f tm.dac -a "$VERSION" = "$cur_version" ]; then
  if cmp -s $dir/tm.dac tm.dac; then
	MYPATH="$PWD:"
  else
	echo $appname: WARNING!: $PWD/tm.dac differs but VERSIONs do not >&2
  fi
fi
function eval_dir {
  typeset bin=$1
  if [ -d $bin ]; then
	bin=`fullpath -t $bin`
	[ -f $bin/tm.dac ] ||
	  nl_error Unable to locate $bin/tm.dac
	cmp -s $dir/tm.dac $bin/tm.dac ||
	  nl_error $bin/tm.dac differs but VERSIONs do not
	MYPATH="$MYPATH$bin:"
  fi
}
eval_dir bin/$VERSION
[ $dir/../bin/$VERSION -ef bin/$VERSION ] ||
  eval_dir $dir/../bin/$VERSION

[ -z "$MYPATH" ] &&
  nl_error Unable to locate valid bin directory for version $VERSION

echo $MYPATH
exit 0;
