#! /bin/sh

#__USAGE
#%C
#	Dismount Optical Disk

# Optical Disk Out

if test -z "$OD_NODE"; then
   OD_NODE=$NODE
fi

if [ ! -b //$OD_NODE/dev/od0 ]; then
  echo Unable to locate optical drive: Is OD_NODE defined?
  exit 1
fi

if [ ! -d //$OD_NODE/od ]; then
  echo Optical Disk File System Already Dismounted on node $OD_NODE
elif find //$OD_NODE/od -mountpoint -level 0 -prune >/dev/null; then
  if umount //$OD_NODE/od; then
	echo Optical Disk File System Dismounted Successfully on node $OD_NODE
  else
	echo Optical Disk File System Dismount Failed on node $OD_NODE
	exit 1
  fi
else
  echo //$OD_NODE/od is not a mountpoint!\\a
  exit 1
fi

if [ ! -b //$OD_NODE/dev/od0t77 ]; then
  echo Optical Disk Partitons Already Dismounted on node $OD_NODE
elif umount //$OD_NODE/dev/od0; then
   echo Optical Disk Partitions Dismounted Successfully on node $OD_NODE
else
   echo Optical Disk Partitions unmount failed on node $OD_NODE
   exit 1;
fi
