#! /bin/sh

#__USAGE
#%C	<drive>
#	Dismount Optical Disk
#	<drive> is either od0 or od1

# Optical Disk Out
drive=$1
case $drive in
  od0) :;;
  od1) :;;
  *) echo Must specify od0 or od1; exit 1;;
done

# Optical Drive Disk In
if [ -z "$OD_NODE" ]; then OD_NODE=$NODE; fi
bdrive=//$OD_NODE/dev/$drive
mdrive=//$OD_NODE/$drive
echo Looking at $bdrive

if [ ! -b $bdrive ]; then
  echo Unable to locate optical drive: Is OD_NODE defined?
  exit 1
fi

if [ ! -d $mdrive ]; then
  echo Optical Disk File System Already Dismounted on node $OD_NODE
elif find $mdrive -mountpoint -level 0 -prune >/dev/null; then
  if umount $mdrive; then
	echo Optical Disk File System $mdrive Dismounted Successfully
  else
	echo Optical Disk File System $mdrive Dismount Failed
	exit 1
  fi
else
  echo $mdrive is not a mountpoint!\\a
  exit 1
fi

if [ ! -b ${bdrive}t77 ]; then
  echo Optical Disk Partiton ${bdrive}t77 Already Dismounted
elif umount $bdrive; then
   echo Optical Disk Partition $bdrive Dismounted Successfully
else
   echo Optical Disk Partition umount $bdrive failed
   exit 1;
fi
