#! /bin/sh

#__USAGE
#%C	[-e] <drive>
#	Dismount Optical Disk
#	<drive> is either od0 or od1
#	-e indicates not to eject the disk after dismounting

typeset eject=eject sval

while getopts "e" option; do
  case $option in
	e) eject="";;
	\?) echo; exit 1;;
	*) echo Unsupported option: -$option; exit 1;;
  esac
done
let sval=$OPTIND-1
shift $sval

drive=$1
case $drive in
  od[0-2]) :;;
  *) echo Must specify od0, od1 or od2; exit 1;;
esac

# Optical Drive Disk In
if [ -z "$OD_NODE" ]; then OD_NODE=$NODE; fi
bdrive=//$OD_NODE/dev/$drive
mdrive=//$OD_NODE/$drive
echo Looking at $bdrive

if [ ! -b $bdrive ]; then
  echo Unable to locate optical drive: Is OD_NODE defined?
  exit 1
fi

#----------------------------------------------------------------
# This block translates prefixes when necessary
#----------------------------------------------------------------
set -- `fullpath $bdrive`
[ -n "$3" ] || exit 1
if expr "$3" : //$OD_NODE/dev/\* >/dev/null ; then
  if [ "$bdrive" != "$3" ]; then
	echo $bdrive is really $3
	bdrive=$3
  fi
else
  echo $*: get help!
  exit 1
fi

if [ ! -d $mdrive ]; then
  echo Optical Disk File System Already Dismounted on node $OD_NODE
elif find $mdrive -mountpoint -level 0 -prune >/dev/null; then
  if umount $mdrive; then
	echo Optical Disk File System $mdrive Dismounted Successfully
  else
	echo Optical Disk File System $mdrive Dismount Failed
	exit 1
  fi
else
  echo $mdrive is not a mountpoint!\\a
  exit 1
fi

if [ ! -b ${bdrive}t77 ]; then
  echo Optical Disk Partiton ${bdrive}t77 Already Dismounted
elif umount $bdrive; then
  echo Optical Disk Partition $bdrive Dismounted Successfully
  if [ -x /usr/bin/scsi_util ]; then
	scsi_util -n $OD_NODE $bdrive unlock $eject
  else
	echo You are missing scsi_util. Please osupdate
  fi
else
   echo Optical Disk Partition umount $bdrive failed
   exit 1;
fi
