#! /bin/sh
#__USAGE
#%C	<srcnode> <tgtnode>

typeset debug="no"

################################################################
# Body of the procedure:
# %C	<srcnode> <tgtnode>
#
# Reads command lines from stdin
# Writes non-trivial actions to stdout
# Writes error codes to stderr
# Commands:
#  /[+] <directory> <perms> <owner>
#    Create the directory on the target node if necessary.
#    cd to the directory on the source node
#  <category code> <filename> <special flags>
#    Assuming directories are OK, copy the specified file
#    using the standard options: default is copy only if
#    newer, preserving permissions and verbose:  cp -fpvn
#    For thorough update, might use cp -fpv. -f forces
#    symbolic links to be removed before a file is copied.
#
#    Files which should be symbolically linked to the source
#    file take the special flag 'S'. In this case the soft
#    link is performed if the target file doesn't exist or
#    is not the same as the source file.
#
#    <filename> may specify a directory only in the case
#    of a symbolic link to the source directory.
#
#    Note: for OS updates, modification of certain files
#    should trigger /etc/make_links. Namely anything on
#    the left side of ln -f should trigger make_links and
#    anything on the right side should be excluded from the
#    list. Files followed by an M are so designated.
################################################################
typeset src=$1 tgt=$2
typeset tgtdir srcdir catcode fname flags owner os_links="no" severity=0
typeset timefile file paxfile

if [ -z "$src" -o -z "$tgt" ]; then
  echo "update_node: Missing source ($src) or target ($tgt) definition" >&2
  exit 1
fi
if [ ! -d //$src/ ]; then
  echo Source node //$src/ unreachable >&2
  exit 1
fi
tgt=`echo $tgt | tr [A-Z] [a-z]`
timefile=//$src/etc/config/update.$tgt
paxfile=$TMPDIR/$tgt.pax
[ -f $timefile ] && timed=yes

cat >message_file <<-THE_END




             Harvard University Atmospheric Research Project

                    Data Acquisition Architecture

                        Installation Package






THE_END
message_file=yes

while read catcode fname flags owner; do
  if [ -n "$message_file" ]; then
	echo "message_file"
	unset message_file
  fi
  case $catcode in
	#*) :;;
	\/*)
	  echo //$src$fname
	  tgtdir=$fname/; srcdir=//$src$fname/;;
	*)
	  case $flags in
		*P*)
		  ;;
		*[HSs]*)
		  # linked files (not supported?)
		  echo Error: $srcdir$fname linked via $flags in host update >&2
		  severity=1;;
		*)
		  # we ignore the soft link with regular files
		  # just output the file if it meets the criteria?
		  for file in $srcdir$fname; do
			if [ -d "$file" ]; then
			  if [ -z "$timed" ]; then
				find $file -type f
			  else
				find $file -type f -newer $timefile
			  fi
			elif [ -f "$file" ]; then
			  [ -z "$timed" -o "$file" -nt $timefile ] &&
				echo $file
			fi
		  done;;
	  esac;;
  esac
done | pax -wv -s,//$src,, -s,message_file,/dev/tty, > $paxfile

touch $timefile

rm message_file

pax -v <$paxfile | grep "^-rws" | awk '{print "/bin/chmod o-rw,u+s " $NF}' >setup
chmod a+x setup
pax -a -f $paxfile setup
rm setup

freeze -f $paxfile

echo Archive written to $paxfile.F

exit $severity
