#! /bin/sh
#__USAGE
#%C	[-t] [host [port]]
#	-t Don't redefine TERM
#	Sets terminal to vt102 and connects to the specified host.
#	If the host is "molly", vt100 will connect via rlogin,
#	otherwise telnet is used.
#	e.g.   vt100 hollis
typeset d_term=yes
while getopts "t" option; do
  case $option in
	t) d_term=no;;
	\?) echo; exit 1;;
	*) echo Unsupported option: -$option; exit 1;;
  esac
done
let sval=$OPTIND-1
shift $sval

# This effectively ignores ^C, so the terminal will be reset
# properly.
trap : INT
typeset host port
host="${1:-molly}"
[ -z "$host" ] && host="molly"
[ -n "$1" ] && port="$2"
command=telnet
[ "$host" = molly -a -z "$port" ] && command=rlogin
stty protocol=1 term=vt102
[ "$d_term" = "yes" ] && export TERM=vt102
# echo TERM is $TERM, command is $command, host is $host, port is $port
$command $host $port
stty protocol=0 term=qnx
