#! /bin/sh
#__USAGE
#%C	[-t] [-T] host [port]
#	-t Don't redefine TERM
#	-T use telnet instead of ssh
#	Sets terminal to vt102 and connects to the specified host.
#   The default terminal emulator is ssh
#
#	e.g.   vt100 abigail
typeset d_term=yes d_ssh=yes
while getopts "t" option; do
  case $option in
	t) d_term=no;;
	T) d_ssh=no;;
	\?) echo; exit 1;;
	*) echo Unsupported option: -$option; exit 1;;
  esac
done
let sval=$OPTIND-1
shift $sval
typeset host port
host="$1"
if [ -z "$host" ]; then
  echo "vt100: Must specify a host" >&2
  exit 1
fi
port="$2"

# This effectively ignores ^C, so the terminal will be reset
# properly.
trap : INT
command=telnet
[ "$d_ssh" = "yes" -a -z "$port" ] && command=ssh
stty protocol=1 term=vt102
[ "$d_term" = "yes" ] && export TERM=vt102
# echo TERM is $TERM, command is $command, host is $host, port is $port
$command $host $port
stty protocol=0 term=qnx
