# include definitions
include $(SRCDIR)/src.mk
SUBDIRS =
HOMEDIR = $(DASDIR)/dbr/mods/dcs/fdout
BASE = fdout

# file list macros
TXTS += $(USEDIR)/dc.txt $(USEDIR)/das.txt $(USEDIR)/eillib.txt
SRCS += fdout_dc.c
LIBS = dbr

# include targets
include $(DASDIR)/tgt.mk
