# include definitions
include $(SRCDIR)/src.mk
SUBDIRS =
HOMEDIR = $(DASDIR)/dfs/mods/dcs/lgr/plgr
BASE = lgr

# file list macros
TXTS += $(USEDIR)/dc.txt $(USEDIR)/msg.txt $(USEDIR)/cc.txt
HDRS = 
SRCS += lgr_dc.c
LIBS = dfs dfs_mod eillib

# include targets
include $(DASDIR)/tgt.mk
