# include definitions
include $(SRCDIR)/src.mk
SUBDIRS =
HOMEDIR = $(DASDIR)/dfs/mods/dgs/dgin
BASE = dgin

# file list macros
TXTS += $(USEDIR)/dg.txt $(USEDIR)/das.txt $(USEDIR)/msg.txt
LIBS = dfs das nortlib
SRCS += dgin_dg.c

# include targets
include $(DASDIR)/tgt.mk
