# include definitions
include $(SRCDIR)/src.mk
SUBDIRS =
HOMEDIR = $(DASDIR)/dfs/mods/dcs/demo
BASE = demo

# file list macros
TXTS += $(USEDIR)/dc.txt $(USEDIR)/msg.txt $(USEDIR)/cc.txt
HDRS = 
SRCS += demo_dc.c
LIBS = dbr eillib das

# include targets
include $(DASDIR)/tgt.mk
