include $(SRCDIR)/src.mk
MNC = dfsmod
SUBDIRS =  dbs dbs
SUBDIRS += dcs dcs
SUBDIRS += dbs dgs
SUBDIRS += lib dfsmodlib
SUBDIRS += utils dfsmodutils
HOMEDIR = $(DASDIR)/dfs/mods
SRCS =
HDRS =
TXTS =

all:

