# include definitions
include $(SRCDIR)/src.mk
SUBDIRS =
HOMEDIR = $(DASDIR)/dbr/mods/dcs/filter
BASE = filter

# file list macros
TXTS += $(USEDIR)/msg.txt $(USEDIR)/dc.txt
LIBS = dbr das
SRCS += filter_dc.c

# include targets
include $(DASDIR)/tgt.mk
