# include definitions
include $(SRCDIR)/src.mk
SUBDIRS =
HOMEDIR = $(DASDIR)/dfs/mods/dcs/busout
BASE = busout

# file list macros
TXTS += $(USEDIR)/dc.txt $(USEDIR)/das.txt $(USEDIR)/msg.txt
SRCS += busout_dc.c
LIBS = dfs dfs_mod

# include targets
include $(DASDIR)/tgt.mk
