extern int getlist(char fnames[], char *ptrs[], int diskflag, int sysflag);
extern void freememory(void);
extern int getproject(void);
extern void up_file(void);
extern void com_file(void);
extern void add_file(void);
extern void del_file(void);
extern void list_file(void);
extern void cop_sys(void);
extern void add_sys(void);
extern void up_sys(void);
extern void com_sys(void);
extern void del_sys(void);
extern void list_sys(void);
extern void cop_project(void);
extern void up_project(void);
extern void com_project(void);
extern void add_project(void);
extern void del_project(void);
extern void list_project(void);
extern void request(void);
extern int writefile(char *filename);