# include definitions
include $(SRCDIR)/src.mk
SUBDIRS =
HOMEDIR = $(DASDIR)/mods/pif
BASE = pif

# file list macros
LIBS = das
TXTS += $(USEDIR)/das.txt $(USEDIR)/msg.txt $(USEDIR)/serial.txt
SRCS += crc.c

# include targets
include $(DASDIR)/tgt.mk

# add perms to all
all : perms

