# include definitions
include $(SRCDIR)/src.mk
SUBDIRS =
HOMEDIR = $(DASDIR)/dfs/mods/dcs/serout
BASE = serout

# file list macros
TXTS += $(USEDIR)/dc.txt $(USEDIR)/das.txt $(USEDIR)/eillib.txt
LIBS = dbr das

# include targets
include $(DASDIR)/tgt.mk
