# include definitions
include $(SRCDIR)/src.mk
SUBDIRS =
HOMEDIR = $(DASDIR)/dfs/mods/dcs/serout/old
BASE = serout

# file list macros
TXTS += $(USEDIR)/dc.txt $(USEDIR)/das.txt $(USEDIR)/eillib.txt
SRCS += serout_dc.c
LIBS = dbr eillib

# include targets
include $(DASDIR)/tgt.mk
