# include definitions
include $(SRCDIR)/src.mk
SUBDIRS =
HOMEDIR = $(DASDIR)/dfs/mods/dcs/crc
BASE = crc

# file list macros
TXTS += $(USEDIR)/dc.txt $(USEDIR)/das.txt $(USEDIR)/msg.txt
SRCS += crc_dc.c
LIBS = dfs dfs_mod

# include targets
include $(DASDIR)/tgt.mk
