# include definitions
include $(SRCDIR)/src.mk
SUBDIRS = 
HOMEDIR = $(DASDIR)/dfs/mods/dbs/dggw
BASE = dggw

# file list macros
TXTS += $(USEDIR)/dc.txt $(USEDIR)/dg.txt $(USEDIR)/msg.txt $(USEDIR)/cc.txt
SRCS += dggw_dc.c dggw_dg.c
LIBS = dfs_mod dfs das

# include targets
include $(DASDIR)/tgt.mk

# dependencies
