# include definitions
include $(SRCDIR)/src.mk
SUBDIRS = 
HOMEDIR = $(DASDIR)/mods/utils/spwnr
BASE = spwnr

# file list macros
LIBS = eillib

# include targets
include $(DASDIR)/tgt.mk

# add perms to all
all : perms

# dependencies
