# makefile for /usr/local/include
# $Id$
# $Log$
# Revision 1.11  1993/01/14  18:52:31  nort
# *** empty log message ***
#
# Revision 1.10  1993/01/09  15:51:40  nort
# *** empty log message ***
#
# Revision 1.9  1992/09/30  20:06:28  nort
# Eil added reboot.h
#
# Revision 1.8  1992/09/24  20:25:06  nort
# An update
#
# Revision 1.7  1992/09/09  18:45:23  nort
# Latest version
#
# Revision 1.6  1992/08/20  20:59:54  nort
# More targets
#
# Revision 1.5  1992/07/16  19:13:54  nort
# Changes relative to maintenance.
#
# Revision 1.4  1992/07/15  18:11:58  nort
# Changed Maintenance target to use 'include'
#
# Revision 1.3  1992/06/18  19:27:41  nort
# Updated standard maintenance targets.
#
# Revision 1.2  1992/05/19  21:13:51  nort
# Got rid of "tmc"
#
# Revision 1.1  1992/05/19  18:30:10  nort
# Initial revision
#
SRC=dac.h dbr.h globmsg.h file.h
SRC+=eillib.h das.h dbr_mod.h
SRC+=msg.h sounds.h symname.h timing.h usage.h curses.h company.h
SRC+=lat.h cmdctrl.h subbus.h maint.mk break.h cc.h diaglib.h
SRC+=memlib.h ssp.h snafuerr.h nortlib.h collect.h indexer.h
SRC+=colmain.skel extmain.skel timerbd.h soldrv.h reboot.h
SRC+=cmdalgo.h nl_cons.h cmdalgo.tmc tmctime.h nav.h
SRC+=serial.h spawn.h maint.mk2 rcsmaint.mk dccc.h memo.h scdc.h
SRC+=filename.h frame.h sights.h vector.h libmaint.mk
SRC+=beeps.h reply.h get_priv.h solfmt.h
TOOL=Makefile

SOURCE=$(SRC) $(TOOL)
HOMEDIR=/usr/local/include
MNC=linc
SUBDIRS=use iuse

