include $(SRCDIR)/src.mk
BASE = dasmods
SUBDIRS =  cmdctrl cmdctrl
SUBDIRS += dccc dccc
SUBDIRS += nav nav
SUBDIRS += pif pif
SUBDIRS += scdc scdc
SUBDIRS += scicmd scicmd
SUBDIRS += sol sol
SUBDIRS += utils dasmodutils
HOMEDIR = $(DASDIR)/mods
DOCS = 
SRCS =
HDRS =
TXTS =

all:
