HOMEDIR=/usr/local/include/oui
MNC=ouilib

TOOL=Makefile
SRC=break.oui
SRC+=client.oui
SRC+=cmdctrl.oui
SRC+=compiler.oui
SRC+=dc.oui
SRC+=collect.oui dg.oui
SRC+=dgdacin.oui
SRC+=msg.oui msghdr.oui
SRC+=nl_cons.oui
SRC+=serial.oui
SRC+=seteuid.oui
SRC+=tma.oui
SRC+=subbus.oui subbus_reqd.oui subbus_opt.oui
SOURCE=$(SRC) $(TOOL)
