# include definitions
include $(SRCDIR)/src.mk
SUBDIRS =
HOMEDIR = $(DASDIR)/dbr/mods/utils/stuffer
BASE = stuffer

# file list macros
TXTS += $(USEDIR)/msg.txt $(USEDIR)/stream.txt
LIBS = dbr das

# include targets
include $(DASDIR)/tgt.mk
