# include definitions
include $(SRCDIR)/src.mk
SUBDIRS =
HOMEDIR = $(DASDIR)/dfs/mods/dgs/busin
BASE = busin

# file list macros
TXTS += $(USEDIR)/dg.txt $(USEDIR)/msg.txt
LIBS = dfs das
SRCS += busin_dg.c

# include targets
include $(DASDIR)/tgt.mk
