# include definitions
include $(SRCDIR)/src.mk
SUBDIRS =
HOMEDIR = $(DASDIR)/dfs/mods/dgs/serin/old
BASE = serin

# file list macros
TXTS += $(USEDIR)/dg.txt $(USEDIR)/das.txt $(USEDIR)/eillib.txt
LIBS = dbr das nortlib eillib
SRCS += serin_dg.c

# include targets
include $(DASDIR)/tgt.mk
