#! /bin/sh
#__USAGE
#%C	[options]
#Counts Log Files
#	-d <dirname>
#	-r <rootname>
#	-E output with lables
#	-O output DAS logger/reader options

dirname=$PWD
rootname=log
outopt=d

while getopts d:r:EO opt $*
do
	case $opt in
		d) dirname=$OPTARG;;
		r) rootname=$OPTARG;;
		E) outopt=e;;
		O) outopt=o;;
		\?) echo; exec use $0;;
	esac
done

typeset -i low=-1 high=-1 i=0 lastd=0 curd=0 fpd=0 numdirs=0 ky=0

let ky=${#$dirname}+1
dirs=`/bin/find $dirname -logical -level 1 -prune -type d -name $rootname\[0-9\]\[0-9\]\[0-9\]\[0-9\] -print | /bin/sort -k 0.$ky`

numdirs=`echo $dirs |wc -w`

for j in $dirs
do
   let lastd=curd
   f=`/bin/basename $j`
   curd=${f##$rootname}
   let i=i+1
   if test $i -ne 1 -a $i -ne $numdirs
   then
       continue
   fi
   let ky=${#$j}+${#$rootname}+1
   if test $i -eq 1
   then
       files=`/bin/find $j -logical -level 1 -prune -type f -name $rootname\[0-9\]\[0-9\]\[0-9\]\[0-9\] -print | /bin/sort -k 0.$ky | head -n1`
       f=`/bin/basename $files`
       low=${f##$rootname}
   else
       files=`/bin/find $j -logical -level 1 -prune -type f -name $rootname\[0-9\]\[0-9\]\[0-9\]\[0-9\] -print | /bin/sort -k 0.$ky | tail -n1`
       f=`/bin/basename $files`
       high=${f##$rootname}
   fi
done

# get files per directory, if only 1 dir, then fpd=0
let fpd=curd-lastd

# output
case $outopt in
    d) echo $low $high $fpd $dirname $rootname;;
    e) echo First Log File Number: $low
       echo Last Log File Number: $high
       echo Files per Directory: $fpd
       echo Directiry: $dirname
       echo Rootname: $rootname;;
    o) printf "-L %s -N %s -F %s -d %s -r %s" $high $fpd $low $dirname $rootname;;
   \?) exit 1;;
esac
