#CFLAGS += -2 -ml -g
CFLAGS += -3 -mf

OBJS=        stch_i.o     stcpm.o      stptok.o     strsrt.o     \
argopt.o     stcarg.o     stch_l.o     stcpma.o     strbpl.o     stspfp.o     \
fopene.o     stccpy.o     stci_d.o     stcu_d.o    \
stcd_i.o     stcl_d.o     stcul_d.o    strins.o    \
getpf.o      stcd_l.o     stcl_h.o     stdlib.o     strmfe.o     \
iabs.o       stcgfe.o     stcl_o.o     stpblk.o     strmfn.o     \
stcgfn.o     stco_i.o     stpbrk.o     strmfp.o     \
stcgfp.o     stco_l.o     stpsym.o     strsfn.o     getfnl.o

lat: $(OBJS)

$(OBJS): lat.h
