# master makefile for eil's das source

include $(SRCDIR)/src.mk
BASE = das
SUBDIRS =  lib	daslib
SUBDIRS += mods	dasmods
SUBDIRS += dbr dbr
HOMEDIR = $(DASDIR)
DOCS = tgt.mk
SRCS =
HDRS =
TXTS =

all:
