# include definitions
include $(SRCDIR)/src.mk
SUBDIRS =
HOMEDIR = $(DASDIR)/dbr/mods/dgs/inetin
BASE = inetin
CFLAGS += -g

# file list macros
TXTS += $(USEDIR)/dg.txt $(USEDIR)/das.txt $(USEDIR)/msg.txt
LIBS = dbr

# include targets
include $(DASDIR)/tgt.mk

inetin.o: inetin.c

