# include definitions
include $(SRCDIR)/src.mk
SUBDIRS =
HOMEDIR = $(DASDIR)/dbr/mods/utils/startdfs
BASE = startdfs

# file list macros
TXTS += $(USEDIR)/msg.txt
LIBS = dfs das

# include targets
include $(DASDIR)/tgt.mk
