# include definitions
include $(SRCDIR)/src.mk
SUBDIRS =
BASE = topaz
HOMEDIR = $(DASDIR)/mods/$(BASE)

# CFLAGS += -g
# file list macros
LIBS = das eillib
TXTS += $(USEDIR)/das.txt $(USEDIR)/msg.txt $(USEDIR)/serial.txt
SRCS +=

# include targets
include $(DASDIR)/tgt.mk
