# master makefile for eil's graphics

include $(SRCDIR)/src.mk
BASE = graphics
SUBDIRS = curses curses
SUBDIRS += key key
SUBDIRS += scrdes scrdes
SUBDIRS += scrpaint scrpaint
SUBDIRS += utils grutils
HOMEDIR = $(SRCDIR)/$(BASE)
DOCS = 
SRCS =
HDRS =
TXTS =
USES =

all:
