# include definitions
# Make in 16 bit, -2
include $(SRCDIR)/src.mk
SUBDIRS =
BASE = idler
HOMEDIR = $(DASDIR)/mods/$BASE


# file list macros
LIBS = das
TXTS += $(USEDIR)/das.txt $(USEDIR)/msg.txt

# include targets
include $(DASDIR)/tgt.mk

# add perms to all
# all : perms

